name: Build core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: mkdir
      run: mkdir bin
    - name: cd bin
      run: cd bin
    - name: cmake
      run: cmake ..
    - name: make
      run: make
